In [ ]:
pwd

'/content'

In [ ]:
# 为了了解图像本质，我们需要先了解一下数组和矩阵的概念

In [ ]:
# 首先回忆一下，如何创建一个列表

list_a = [1,2,3,4,5]

In [ ]:
# 打印一下
list_a

[1, 2, 3, 4, 5]

In [ ]:
# 使用type命令查看数据类型，
type(list_a)

list

In [ ]:
# 可以看到是Python的列表

In [ ]:
# 再创建一个列表，使这个列表的元素仍然是列表

In [ ]:
list_b = [ [1,2], [3,4], [5,6]  ]

In [ ]:
# 打印列表
list_b

[[1, 2], [3, 4], [5, 6]]

In [ ]:
# 通过找数字索引，打印第list_b第2个元素的第1个元素
list_b[1][0]

3

In [ ]:
# 这种结构我们也叫数组，比如list_a是一维数组，list_b是二维数组

In [ ]:
# 为了更高效的处理数组，我们常用numpy在这个包

In [ ]:
# 首先导入numpy包，重命名一下
import numpy as np

In [ ]:
# 那numpy如何创建数组呢？
# 可以用Python列表直接转换

In [ ]:
# 首先创建一个Python 列表
list_c = [1,2,3,4]

In [ ]:
# 检查类型
type(list_c)

list

In [ ]:
# 在使用np.array()将Python列表转换为numpy的数组

my_array = np.array(list_c)

In [ ]:
# 我们检查一下my_array的类型，
type(my_array)

numpy.ndarray

In [ ]:
# 可以看到这个变量已经是numpy的数组了

In [ ]:
# 打印一下
my_array

array([1, 2, 3, 4])

In [ ]:
# 那numpy还有一些内置函数可以快速地创建数组

In [ ]:
# 比如我们使用np.arange()可以快速创建连续数字的数组
# 比如我创建一个0~9 的一维数组
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 如果我希望创建0~10中连续偶数的数组，只需将步长设为2（此刻输入np.arange(0,10,2)）

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
# 还可以用np.ones创建全是1的数组，（此时输入np.ones()，弹出帮助说明）
# 比如我要创建一个大小为3*3的全1数组

np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 再创建一个大小为10*3的全1数组
# 可以看到10是行数，3是列数

np.ones(shape=(10,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 或者使用np.zeros()全0数组
# 比如创建大小为5*5的全0数组

np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# 换行

In [ ]:
# 我们再演示一下numpy的一些其他方法

In [ ]:
# 首先使用np.randint函数一些随机整数
arr = np.random.randint(0,100,10)

In [ ]:
# 打印一下
arr

array([44, 96, 53, 30, 26, 34, 15, 33, 50, 19])

In [ ]:
# 使用max获取最大值
arr.max()

96

In [ ]:
# 再使用argmax() 获取最大值的索引
arr.argmax()

1

In [ ]:
# 使用min函数获取最小值
arr.min()

15

In [ ]:
# 使用argmin获取最小值索引
arr.argmin()

6

In [ ]:
# 使用mean()方法获取取平均值
arr.mean()

40.0

In [ ]:
# 如果要获取humpy数组的大小，使用numpy.shape，
arr.shape

(10,)

In [ ]:
# 也可以使用reshape函数转换数组的形状，比如我将arr转换成5*2的数组
arr.reshape((5,2))

array([[44, 96],
       [53, 30],
       [26, 34],
       [15, 33],
       [50, 19]])

In [ ]:
# 可以看到变成了5行2列

In [ ]:
# 再变形成2行5列
arr.reshape((2,5))

array([[44, 96, 53, 30, 26],
       [34, 15, 33, 50, 19]])

In [ ]:
# 如果尝试变形为大小为2*10呢？看看效果
arr.reshape((2,10))

ValueError: cannot reshape array of size 10 into shape (2,10)

In [ ]:
# 可以看到报错了，因为变形后的元素要求是20个，而我们原数组只有10个元素

In [ ]:
# 那二维数组，我们在数学上也称为矩阵，我们再看一下numpy对矩阵的操作

In [ ]:
# 首先创建一个10*10 的矩阵
matrix = np.arange(0,100).reshape((10,10))

In [ ]:
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# 查看一下大小
matrix.shape

(10, 10)

In [ ]:
# 使用中括号中加索引方式，获取矩阵对应元素，比如我获取第3行第5列元素
matrix[2,4]

24

In [ ]:
# 再获取矩阵第9行第7列元素
matrix[8,6]

86

In [ ]:
# 如果要获取某一行所有元素，我们需要使用numpy的切片：
# 比如我要获取第3行所有元素，只需将第二个位置变成冒号:
matrix[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
# 类似的，比如我要获取第6列所有元素，只需将第一个位置变成冒号:
matrix[:,5]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [ ]:
# 查看shape
matrix[:,5].shape

(10,)

In [ ]:
# 用reshape恢复成原来的样子
matrix[:,5].reshape((10,1))

array([[ 5],
       [15],
       [25],
       [35],
       [45],
       [55],
       [65],
       [75],
       [85],
       [95]])

In [ ]:
# 我们再说numpy获取矩阵一个区域的用法
# 再看一下输出一下原来的matrix
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# 比如我要获取第1~3行，第2~4列矩阵，我们可以用数字配合冒号的方式来获取

matrix[0:3,1:4]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [ ]:
# 当然我们可以使用等号赋值语句，比如我将这些位置赋值0
matrix[0:3,1:4] = 0

In [ ]:
# 查看新的矩阵长啥样
matrix

array([[ 0,  0,  0,  0,  4,  5,  6,  7,  8,  9],
       [10,  0,  0,  0, 14, 15, 16, 17, 18, 19],
       [20,  0,  0,  0, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
# 好，以上就是numpy对数组和矩阵的操作用法