In [ ]:
import torch

1. 将二维列表 [[5,3], [0,9]] 转换为一个张量

In [ ]:
data = [[5, 3], [0, 9]]
x_data = torch.tensor(data)

2. 使用区间 [0, 1) 上均匀分布的随机数创建形状 (5, 4) 的张量“t”

In [ ]:
t = torch.rand((5,4))

3. 找出张量“t”所在的设备及其数据类型。


In [ ]:
print(t.device) # cpu
print(t.dtype) # float32

cpu
torch.float32


4. 创建形状 (4,4) 和 (4,4) 的两个随机张量，分别称为“u”和“v”。将它们连接起来形成形状为 (8, 4) 的张量。

In [ ]:
u = torch.randn((4,4))
v = torch.randn((4,4))
print(torch.concat((u,v), dim=0).shape) # torch.Size([8, 4])

torch.Size([8, 4])


5. 连接 u 和 v 以创建形状 (2, 4, 4) 的张量。

In [ ]:
print(torch.stack((u,v), dim=0).shape) # torch.Size([2, 4, 4])

torch.Size([2, 4, 4])


6. 连接 u 和 v 形成一个张量，称为形状 (4, 4, 2) 的 w。

In [ ]:
w = torch.stack((u,v), dim=2)
print(w.shape) # torch.Size([4, 4, 2])

torch.Size([4, 4, 2])


7. 索引 w 位于 3, 3, 0。将该元素称为“e”。

In [ ]:
e = w[3,3,0]

8. 会在 u 或 v 的哪一个中找到 w？并核实。

In [ ]:
# in u
w[3,3,0] == u[3,3] # True

tensor(True)

9. 创建一个形状为 (4, 3) 的全为 1 的张量 ‘a’。对 ‘a’ 进行元素级别的自乘操作。

In [ ]:
a = torch.ones((4,3))
a * a # tensor([[1., 1., 1.],[1., 1., 1.],[1., 1., 1.],[1., 1., 1.]])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

10. 向“a”添加一个额外的维度（新的第 0 维度）。

In [ ]:
print(torch.unsqueeze(a, 0).shape) # torch.Size([1, 4, 3])

torch.Size([1, 4, 3])


11. 执行 a 与转置矩阵的乘法。

In [ ]:
a @ a.T # tensor([3., 3., 3., 3.],[3., 3., 3., 3.],[3., 3., 3., 3.],[3.,

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

12. a.mul(a) 会产生什么结果？

In [ ]:
# An elementwise multiplication, same as #9

13. a.matmul(a.T) 会产生什么结果？

In [ ]:
# A matrix multiplication aka dot product, same as #11

14. What would a.mul(a.T) result in?

In [ ]:
# An error; the sizes won’t match.

15. 猜猜下面会打印什么。验证一下

In [ ]:
t = torch.ones(5)
n = t.numpy()
n[0] = 2
print(t)

tensor([2., 1., 1., 1., 1.])


16. 下面会打印什么？

In [ ]:
t = torch.tensor([2., 1., 1., 1., 1.])
t.add(2)
t.add_(1)
print(n)